### ISSUE TITLE
App down

### ISSUE THREAD

**Issue by joooohaaaan** [bobpoekert/heroku_proxy#1]
Hello,

I noticed yesterday that the app http://www.corsproxy.com/ was down on Heroku. So I'm just wondering when the app went down and what is the reason? Will it be back up again?

Thanks for this app. Been using it from time to time.

**Comment by bobpoekert** [comment]
Whether it will be back up again depends on what Heroku does. They pulled it without warning because it was having negative interactions with their host infrastructure and it's been taking a while to get them to re-enstate it.
